---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: catalogue
  name: catalogue-db
spec:
  selector:
    matchLabels:
      app: catalogue-db
  template:
    metadata:
      labels:
        app: catalogue-db
    spec:
      containers:
      - name: database
        image: postgres:13.8-bullseye
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
        env:
        - name: POSTGRES_PASSWORD
          value: "catalogue"
        - name: POSTGRES_USER
          value: "catalogue"
        - name: POSTGRES_DB
          value: "catalogue"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  namespace: catalogue
  name: "catalogue-db-service"
spec:
  selector:
    app: catalogue-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: catalogue
  name: catalogue-migrator
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: migrator
        image: catalogue:latest
        command:
        - "alembic"
        - "upgrade"
        - "head"
        resources:
          limits:
            memory: "200Mi"
            cpu: "250m"
        env:
        - name: "CATALOGUE_DB_HOST"
          value: "catalogue-db-service"
      initContainers:
      - name: wait-for-db
        image: toschneck/wait-for-it:latest
        command: ["./wait-for-it.sh", "-t", "60", "catalogue-db-service:5432"]
      restartPolicy: Never

---
