version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
      target: prod
    image: catalogue:${CATALOGUE_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      CATALOGUE_HOST: 0.0.0.0
      CATALOGUE_DB_HOST: catalogue-db
      CATALOGUE_DB_PORT: 5432
      CATALOGUE_DB_USER: catalogue
      CATALOGUE_DB_PASS: catalogue
      CATALOGUE_DB_BASE: catalogue
      CATALOGUE_REDIS_HOST: catalogue-redis
      TESTKAFKA_KAFKA_BOOTSTRAP_SERVERS: '["catalogue-kafka:9092"]'

  db:
    image: postgres:16.2-bullseye
    hostname: catalogue-db
    environment:
      POSTGRES_PASSWORD: "catalogue"
      POSTGRES_USER: "catalogue"
      POSTGRES_DB: "catalogue"
    volumes:
    - catalogue-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U catalogue
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: catalogue:${CATALOGUE_VERSION:-latest}
    restart: "no"
    command: alembic upgrade head
    environment:
      CATALOGUE_DB_HOST: catalogue-db
      CATALOGUE_DB_PORT: 5432
      CATALOGUE_DB_USER: catalogue
      CATALOGUE_DB_PASS: catalogue
      CATALOGUE_DB_BASE: catalogue
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "catalogue-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50

  zookeeper:
    image: "bitnami/zookeeper:3.7.1"
    hostname: "catalogue-zookeeper"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_LOG_LEVEL: "ERROR"
    healthcheck:
      test: zkServer.sh status
      interval: 1s
      timeout: 3s
      retries: 30

  kafka:
    image: "bitnami/kafka:3.2.0"
    hostname: "catalogue-kafka"
    environment:
      KAFKA_BROKER_ID: "1"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://catalogue-kafka:9092"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "catalogue-zookeeper:2181"
    healthcheck:
      test: kafka-topics.sh --list --bootstrap-server localhost:9092
      interval: 1s
      timeout: 3s
      retries: 30
    depends_on:
      zookeeper:
        condition: service_healthy

volumes:
  catalogue-db-data:
    name: catalogue-db-data
