"""empty message

Revision ID: 9514a8d5e543
Revises: 8eb05d16b8ee
Create Date: 2024-04-28 19:41:01.968779

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9514a8d5e543"
down_revision = "8eb05d16b8ee"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
