"""empty message

Revision ID: 3ea9e34e9453
Revises: 9514a8d5e543
Create Date: 2024-04-30 16:06:18.175027

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3ea9e34e9453"
down_revision = "9514a8d5e543"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
