"""empty message

Revision ID: 358373f7dec6
Revises: 819cbf6e030b
Create Date: 2024-01-29 20:32:28.252197

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "358373f7dec6"
down_revision = "819cbf6e030b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column(
            "allowed_attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("seo_title", sa.String(length=255), nullable=False),
        sa.Column("seo_description", sa.String(length=255), nullable=False),
        sa.Column("seo_keywords", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category_img_url", sa.String(length=255), nullable=False),
        sa.Column("requires_shipping", sa.Boolean(), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "attribute_options",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("attribute_name", sa.String(length=50), nullable=False),
        sa.Column("value", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
        ),
        sa.PrimaryKeyConstraint("category_id", "attribute_name", "value"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attribute_options")
    op.drop_table("categories")
    # ### end Alembic commands ###
